### ISSUE TITLE
"magic mime db is already open" error

### ISSUE THREAD

**Issue by 1tayH** [maliceio/malice-fileinfo#3]
Hi,
Thanks for this awesome tool, really makes my work a lot easier.

I ran into an issue while trying to automate the web service, it happens when I submit the same file multiple times, not simultaneously:
`fileinfo_1  | 2018/07/06 15:44:28 cannot open; magic mime db is already open` 

any help would be highly appreciated 👍

**Comment by blacktop** [comment]
That was a dumb race condition.  This was my first MaliceIO plugin and I was trying to get fancy with concurrency to minimize the scan time as much as possible.  I believe I have fixed the issue.

Please feel free to reopen this issue it the problem persists.
