### ISSUE TITLE
Concurrent requests

### ISSUE THREAD

**Issue by 1tayH** [maliceio/malice-fileinfo#4]
Hi,
I ran into this weird bug when sending multiple API requests concurrently, this makes one request affect the response of other requests.

This can be reproduced using Apache Benchmark:

`ab -n 10000 -c 1 -p post_data.txt -T "multipart/form-data; boundary=f" http://localhost:3993/scan`
the `post_data.txt` file holds the form data with the **TXT file**. 

Send another request providing a **PE file**, while `ab` is running:
```
$ curl -i -X POST -H "Content-Type: multipart/form-data" -F "malware=@zeus.exe" http://localhost:3993/scan
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Mon, 20 Aug 2018 10:20:26 GMT
Content-Length: 1380

{
   "magic":{
      "mime":"text/plain",
      "description":"**ASCII text, with very long lines, with no line terminators**"
   },
   "ssdeep":"6144:WmNxBCD65shMJmpdFvuKmZEPi4rj2/kH+/MH:WoWD0shvdhqEa4HOmIMH",
   "trid":[
      "**82.7% (.EXE) Win32 Executable Microsoft** Visual Basic 6 (82067/2/8)",
      "6.6% (.DLL) Win32 Dynamic Link Library (generic) (6578/25/2)",
      "4.5% (.EXE) Win32 Executable (generic) (4508/7/1)",
      "2.0% (.EXE) OS/2 Executable (generic) (2029/13)",
      "2.0% (.EXE) Generic Win/DOS Executable (2002/3)"
   ],
   "exiftool":{
      "CharacterSet":"Unicode",
      "CodeSize":"307200",
      "Comments":"Scribblative",
      "CompanyName":"NCH Software",
      "EntryPoint":"0x11b8",
      "ExifToolVersionNumber":"11.06",
      "FileDescription":"Redcrested2",
      "FileFlags":"(none)",
      "FileFlagsMask":"0x0000",
      "FileOS":"Win32",
      "FileSize":"316 kB",
      "FileSubtype":"0",
      "FileType":"Win32 EXE",
      "FileTypeExtension":"exe",
      "FileVersion":"1.00",
      "FileVersionNumber":"1.0.0.0",
      "ImageVersion":"1.0",
      "InitializedDataSize":"24576",
      "InternalName":"Infraglacial2",
      "LanguageCode":"Chinese (Traditional)",
      "LinkerVersion":"6.0",
      "MIMEType":"application/octet-stream",
      "MachineType":"Intel 386 or later, and compatibles",
      "OSVersion":"4.0",
      "ObjectFileType":"Executable application",
      "OriginalFileName":"Infraglacial2.exe",
      "PEType":"PE32",
      "ProductName":"Touch",
      "ProductVersion":"1.00",
      "ProductVersionNumber":"1.0.0.0",
      "Subsystem":"Windows GUI",
      "SubsystemVersion":"4.0",
      "UninitializedDataSize":"0"
   }
}
```
As you can see according to Magic it's a text file while Trid and Exiftool say it's PE, Magic is the only service that is effected by this as you can see. 
If we stop AB from making requests, fileinfo processes the file fine and Magic detects it as PE as intended

Thank you again for making this tool, any help would be appreciated 😄

**Comment by blacktop** [comment]
Hmmm that is very strange.  I wonder if it is a collision in temp file names?

**Comment by blacktop** [comment]
That last commit might fix it.  Once it is done building in DockerHUB can you try again?

**Comment by 1tayH** [comment]
Still doesn't seem to work properly unfortunately. 
I don't think it's the issue because it only happens with `magic` and the tmpfile is being used with trid, ssdeep and exiftool as well and those seem to work just fine
also https://golang.org/src/io/ioutil/tempfile.go is handling randomness by itself pretty well

**Comment by 1tayH** [comment]
Possibly relevant: https://github.com/rakyll/magicmime/pull/22/files

**Comment by tomerf-sndbox** [comment]
See https://github.com/malice-plugins/fileinfo/pull/5/files

**Comment by blacktop** [comment]
@1tayH you are correct that is the problem!! 👍

**Comment by blacktop** [comment]
I was using goroutines before but forgot the mutex. :face_palm:

**Comment by blacktop** [comment]
@tomerf-sndbox what was the bug? some kind of a grid-lock on the DB?

**Comment by blacktop** [comment]
The code used to run this way: https://github.com/malice-plugins/fileinfo/commit/9bc1663494d729d44c121f0eb1caf89613e7f80a#diff-604edda4b54f80f459b9d58a4bf0deceL62 with goroutines and was optimized for speed, but needed mutexes.

**Comment by blacktop** [comment]
I forgot to say @1tayH thank you for running that benchmarking test.  Very cool! I appreciate you helping to make this plugin as good and as stable as it can be. 👍

**Comment by tomerf-sndbox** [comment]
@blacktop I've placed the mutex in the wrong place...

**Comment by blacktop** [comment]
@1tayH have you seen my 2 newest plugins:
- https://github.com/malice-plugins/pescan
- https://github.com/malice-plugins/pdf

They are python based (not go 😢)  I would be currious on how they perform under a large load too?  If you get bored 😉 

I probably need to add uwsgi to them to handle a lot of concurrent connections

**Comment by tomerf-sndbox** [comment]
@blacktop See updated PR

**Comment by blacktop** [comment]
@1tayH can you confirm the mutex fixes your issue once the image is done building in DockerHUB?

**Comment by blacktop** [comment]
Also feel free to close this issue if the problem is fixed.

**Comment by 1tayH** [comment]
Looks like the build failed for some reason, it isn't pushed to Docker Hub

**Comment by tomerf-sndbox** [comment]
@blacktop Dockerhub issues? I can't see the cause

**Comment by blacktop** [comment]
I have been experiencing a LOT of issues with DockerHUB recently.  I have restarted the build now.

**Comment by blacktop** [comment]
@1tayH build is complete

**Comment by 1tayH** [comment]
Works perfectly, thank you!
