### ISSUE TITLE
Upgrade Exiftool for better information

### ISSUE THREAD

**Issue by tomerf-sndbox** [maliceio/malice-fileinfo#9]
Newer Exiftool version (I've tested v11.59) has better file detection capabilities

**Comment by blacktop** [comment]
Thank you

**Comment by tomerf-sndbox** [comment]
Thanks 👍

**Comment by tomerf-sndbox** [comment]
Further research lead me understand that there are missing optional packages that greatly boost exiftool detection

In order to add those:
1. apt-get install file cpanminus (perl package manager)
2. cpanm --notest File::Find Archive::Zip Compress::Raw::Zlib

**Comment by blacktop** [comment]
Does that just allow exiftool to see inside zip files?

**Comment by tomerf-sndbox** [comment]
Please see the discussion here
http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,10454.0.html

**Comment by blacktop** [comment]
Thanks to @jakewarren we can now close this.
